version: '3.4'

services:
  productweb:
    image: ${DOCKER_REGISTRY-}productweb  
    build:  
      context: .  
      dockerfile: ProductWeb/Dockerfile 
    environment:
      - DB_CONNECTION_STRING=Server=sql;Database=outstanding-db;User=sa;Password=Sup3rP@55;encrypt=true;trustServerCertificate=true"
    depends_on:
      - sql
    ports:  
      - '2006:80'  
    expose:  
      - 2006  
    networks:
      - net
  
  sql:  
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu  
    environment:    
      SA_PASSWORD: "Sup3rP@55"
      ACCEPT_EULA: Y
    ports:  
      - '1433'  
    expose:  
      - 1433 
    networks:
      - net

networks:
  net:
    driver: bridge